# Generated by Django 5.1.2 on 2024-10-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankloan',
            fields=[
                ('loan_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('interest', models.IntegerField()),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
